spring:
  application:
    name: freight-svc
  cloud:
    function:
      definition: orderCreatedConsumer
    stream:
      default:
        consumer:
          useNativeDecoding: false
      bindings:
        orderCreatedConsumer-in-0:
          destination: order-created
          group: freight-svc
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
            spring.json.trusted.packages: "*"
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8081